### ISSUE TITLE
Setup description

### ISSUE THREAD

**Issue by Jazzco** [DougRogers/MemLeakDetect#1]
This looks like a promising project. However I can't compile it due to a missing header. I tried it on Windows 11 with VS 2022.
The missing file is `dbgint.h`. Two hours of googling didn't help. The `crtdbg.h` was found, from some similar sources I found an include path of `..\crt\src\dbgint.h` but that path doesn't exist relative to `crtdbg.h`.

Any idea what prerequisites miss?

However, this is only the preparation. The goal would be to get it up and running with a Qt 6 project.

**Comment by DougRogers** [comment]
I added dbgint.h  to the repo.  I am using this for a Qt6 project

**Comment by DougRogers** [comment]
It must have been from an old library source drop.

https://github.com/shihyu/learn_c/blob/master/vc_lib_src/src/dbgint.h

**Comment by Jazzco** [comment]
Great! Thank you.
